### ISSUE TITLE
Introduce support for other datatypes, such as bigint

### ISSUE THREAD

**Issue by justinborromeo** [larrysu1115/cassandra-data-loader#2]

**Comment by justinborromeo** [comment]
And text

**Comment by tesla3** [comment]
I tried with following snip of codes for additional types (not fancy collection or blob ones) in my local repo, it works pretty well so far:

71           case c if c._2 == "ascii" => line.get(i).asInstanceOf[Object]
 72           case c if c._2 == "text" => line.get(i).asInstanceOf[Object]
 73           case c if c._2 == "varchar" => line.get(i).asInstanceOf[Object]
 74           case c if c._2 == "int"     => line.get(i).toInt.asInstanceOf[Object]
 75           case c if c._2 == "bigint"     => line.get(i).toLong.asInstanceOf[Object]
 76           case c if c._2 == "varint"     => BigInt(line.get(i)).asInstanceOf[Object]
 77           case c if c._2 == "decimal"     => BigDecimal(line.get(i)).asInstanceOf[Object]
 78           case c if c._2 == "double"  => line.get(i).toDouble.asInstanceOf[Object]
 79           case c if c._2 == "float"  => line.get(i).toFloat.asInstanceOf[Object]
 80           case c if c._2 == "date"    => (LocalDate.parse(line.get(i)).toEpochDay().toInt + epochMiddle).asInstanceOf[Object]
 81         }
 82
